import { createFileRoute } from "@tanstack/react-router";
import { todayIST, formatTimestampIST } from "@/lib/date-utils";
import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { toast } from "sonner";
import {
  Clock,
  ChevronLeft,
  ChevronRight,
  Flag,
  Loader2,
  Play,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  BarChart3,
  RotateCcw,
  BookOpen,
  Sparkles,
  Timer,
  CircleDot,
} from "lucide-react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { generateMockTest } from "@/lib/ai.functions";
import { getExamById } from "@/lib/exam-catalog";
import { uid, type MockTest, type MockTestSection, type MockTestQuestion } from "@/lib/storage";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useTutorial } from "@/components/TutorialProvider";
import { MarkdownContent } from "@/components/MarkdownContent";

export const Route = createFileRoute("/mock-test")({
  head: () => ({
    meta: [
      { title: "Mock Test — AcePrep" },
      {
        name: "description",
        content: "Take timed, exam-pattern mock tests generated by AI to simulate the real exam.",
      },
    ],
  }),
  component: MockTestPage,
});

type Screen = "setup" | "test" | "result";

function MockTestPage() {
  const queryClient = useQueryClient();
  const { data: profile } = useQuery({ queryKey: ["userProfile"], queryFn: api.getUserProfile });
  const { data: mockTests = [] } = useQuery({ queryKey: ["mockTests"], queryFn: api.getMockTests });
  const examInfo = profile?.exam_id ? getExamById(profile.exam_id) : undefined;
  const { triggerPageTour } = useTutorial();

  useEffect(() => {
    triggerPageTour("mock-test");
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const [screen, setScreen] = useState<Screen>("setup");
  const [currentTest, setCurrentTest] = useState<MockTest | null>(null);

  const saveMutation = useMutation({
    mutationFn: api.saveMockTest,
    onError: (error) => toast.error(error.message || "Operation failed"),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["mockTests"] }),
  });

  const handleStartTest = (test: MockTest) => {
    setCurrentTest(test);
    setScreen("test");
  };

  const handleFinishTest = async (test: MockTest) => {
    setCurrentTest(test);
    try {
      await saveMutation.mutateAsync(test);

      // Auto-save wrong answers as spaced-repetition review cards
      const allQuestions = test.sections.flatMap((s) => s.questions);
      const wrongCards = allQuestions
        .filter((q) => test.answers[q.id] !== q.answerIndex)
        .map((q) => ({
          question: q.question,
          answer: q.options[q.answerIndex],
          explanation: q.explanation || undefined,
          subject: q.section,
          topic: q.topic || undefined,
          source: "mock_test" as const,
          ease_factor: 2.5,
          interval_days: 1,
          repetitions: 0,
          next_review: todayIST(),
        }));
      if (wrongCards.length > 0) {
        api.saveReviewCards(wrongCards).catch(() => {});
      }

      // Award XP for completing the mock test (fire-and-forget)
      api
        .awardXP(50, {
          mockCount: (queryClient.getQueryData<MockTest[]>(["mockTests"])?.length ?? 0) + 1,
        })
        .catch(() => {});

      setScreen("result");
    } catch (e) {
      toast.error("Failed to save test result. Showing results without saving.");
      setScreen("result"); // Still show the result screen so they can see their score
    }
  };

  const handleBackToSetup = () => {
    setCurrentTest(null);
    setScreen("setup");
  };

  return (
    <div className="relative min-h-full">
      <div className="relative">
        {screen === "setup" && (
          <SetupScreen
            examInfo={examInfo}
            profile={profile}
            mockTests={mockTests}
            onStart={handleStartTest}
          />
        )}
        {screen === "test" && currentTest && (
          <TestScreen test={currentTest} onFinish={handleFinishTest} />
        )}
        {screen === "result" && currentTest && (
          <ResultScreen test={currentTest} onBack={handleBackToSetup} />
        )}
      </div>
    </div>
  );
}

/* ──────────── SETUP SCREEN ──────────── */
function SetupScreen({
  examInfo,
  profile,
  mockTests,
  onStart,
}: {
  examInfo: ReturnType<typeof getExamById>;
  profile: import("@/lib/storage").UserProfile | null | undefined;
  mockTests: MockTest[];
  onStart: (test: MockTest) => void;
}) {
  const [generating, setGenerating] = useState(false);
  const [questionsPerSection, setQuestionsPerSection] = useState(5);

  const handleGenerate = async () => {
    if (!examInfo) {
      toast.error("Please complete onboarding first.");
      return;
    }
    setGenerating(true);
    try {
      const sections = examInfo.subjects
        .filter(
          (s) => !profile?.selected_subjects?.length || profile.selected_subjects.includes(s.name),
        )
        .map((s) => ({
          name: s.name,
          questions: questionsPerSection,
          topics: s.topics.slice(0, 8),
        }));

      const res = await generateMockTest({
        data: { examName: examInfo.name, sections, source: "mock-test" },
      });

      const totalQuestions = (res.sections || []).reduce(
        (sum: number, s) => sum + (s.questions?.length || 0),
        0,
      );
      const timePerQ = examInfo.examPattern.totalTimeMinutes / examInfo.examPattern.totalQuestions;
      const totalTimeSeconds = Math.round(totalQuestions * timePerQ * 60);

      const test: MockTest = {
        id: uid(),
        exam_id: examInfo.id,
        exam_name: examInfo.name,
        sections: (res.sections || []).map((s) => ({
          name: s.name,
          timeMinutes: Math.round((s.questions?.length || 0) * timePerQ),
          questions: (s.questions || []).map((q) => ({
            id: uid(),
            question: q.question,
            options: q.options,
            answerIndex: q.answerIndex,
            explanation: q.explanation,
            section: s.name,
            topic: q.topic || s.name,
          })),
        })),
        answers: {},
        total_time_seconds: totalTimeSeconds,
        status: "in_progress",
        started_at: new Date().toISOString(),
      };

      onStart(test);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to generate mock test");
    } finally {
      setGenerating(false);
    }
  };

  const completedTests = mockTests.filter((t) => t.status === "completed");

  return (
    <div className="max-w-4xl mx-auto px-6 py-10 animate-fade-up">
      <h1 className="text-3xl font-bold tracking-tight font-heading">
        <span className="text-gradient">Mock Tests</span>
      </h1>
      <p className="text-muted-foreground mt-2">
        Simulate real exam conditions with timed, AI-generated mock tests.
      </p>

      {/* Generate card */}
      <div className="card-light p-6 rounded-2xl mt-8" data-tour="tour-mock-new">
        <div className="flex items-center gap-3 mb-4">
          <div className="h-11 w-11 rounded-xl bg-gradient-primary grid place-items-center text-white">
            <Sparkles className="h-5 w-5" />
          </div>
          <div>
            <div className="font-semibold font-heading">New Mock Test</div>
            <div className="text-sm text-muted-foreground">
              {examInfo
                ? `${examInfo.icon} ${examInfo.name} pattern`
                : "Complete onboarding to start"}
            </div>
          </div>
        </div>

        {examInfo && (
          <>
            <div className="grid grid-cols-3 gap-3 mb-4">
              <div className="p-3 rounded-xl text-center" style={{ background: "var(--muted)" }}>
                <div className="text-lg font-bold font-heading">
                  {examInfo.examPattern.sections.length}
                </div>
                <div className="text-xs text-muted-foreground">Sections</div>
              </div>
              <div className="p-3 rounded-xl text-center" style={{ background: "var(--muted)" }}>
                <div className="text-lg font-bold font-heading">
                  {examInfo.examPattern.totalTimeMinutes}m
                </div>
                <div className="text-xs text-muted-foreground">Total time</div>
              </div>
              <div className="p-3 rounded-xl text-center" style={{ background: "var(--muted)" }}>
                <div className="text-lg font-bold font-heading">
                  {examInfo.examPattern.markingScheme.split(".")[0]}
                </div>
                <div className="text-xs text-muted-foreground">Marking</div>
              </div>
            </div>

            <div className="mb-4">
              <label className="text-sm font-medium mb-2 block">Questions per section</label>
              <div className="flex gap-2">
                {[3, 5, 10, 15].map((n) => (
                  <button
                    key={n}
                    onClick={() => setQuestionsPerSection(n)}
                    className={cn(
                      "px-4 py-2 rounded-xl text-sm font-medium transition-all",
                      questionsPerSection === n
                        ? "bg-gradient-primary text-white shadow-glow-sm"
                        : "text-muted-foreground hover:opacity-80",
                    )}
                    style={questionsPerSection !== n ? { background: "var(--muted)" } : undefined}
                  >
                    {n}
                  </button>
                ))}
              </div>
            </div>
          </>
        )}

        <Button
          onClick={handleGenerate}
          disabled={generating || !examInfo}
          className="w-full bg-gradient-primary h-12"
        >
          {generating ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin mr-2" /> Generating questions...
            </>
          ) : (
            <>
              <Play className="h-4 w-4 mr-2" /> Start Mock Test
            </>
          )}
        </Button>
      </div>

      {/* Past tests */}
      {completedTests.length > 0 && (
        <div className="mt-8">
          <h2 className="text-lg font-semibold font-heading mb-4">Past Mock Tests</h2>
          <div className="space-y-3" data-tour="tour-mock-list">
            {completedTests.slice(0, 10).map((test) => {
              const pct = test.total_marks
                ? Math.round(((test.score ?? 0) / test.total_marks) * 100)
                : 0;
              const mins = test.time_taken_seconds ? Math.round(test.time_taken_seconds / 60) : 0;
              return (
                <div key={test.id} className="card-light p-4 rounded-2xl flex items-center gap-4">
                  <div
                    className={cn(
                      "h-12 w-12 rounded-xl grid place-items-center text-lg font-bold font-heading",
                      pct >= 70
                        ? "bg-success/10 text-success"
                        : pct >= 40
                          ? "bg-warning/10 text-warning"
                          : "bg-destructive/10 text-destructive",
                    )}
                  >
                    {pct}%
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="font-medium">{test.exam_name}</div>
                    <div className="text-xs text-muted-foreground flex items-center gap-2 mt-0.5">
                      <span>
                        {test.score}/{test.total_marks} marks
                      </span>
                      <span>·</span>
                      <span className="flex items-center gap-1">
                        <Clock className="h-3 w-3" />
                        {mins}m
                      </span>
                      <span>·</span>
                      <span>{test.created_at ? formatTimestampIST(test.created_at) : ""}</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

/* ──────────── TEST SCREEN ──────────── */
function parseMarkingScheme(scheme?: string): { correct: number; wrong: number } {
  if (!scheme) return { correct: 4, wrong: -1 }; // JEE default
  const match = scheme.match(/([+-]?\d+)\/([+-]?\d+)/);
  if (!match) return { correct: 4, wrong: -1 };
  return { correct: parseInt(match[1]), wrong: parseInt(match[2]) };
}

function TestScreen({ test, onFinish }: { test: MockTest; onFinish: (test: MockTest) => void }) {
  const [activeSection, setActiveSection] = useState(0);
  const [activeQuestion, setActiveQuestion] = useState(0);
  const [answers, setAnswers] = useState<Record<string, number | null>>(test.answers || {});
  const [flagged, setFlagged] = useState<Set<string>>(new Set());
  const [timeLeft, setTimeLeft] = useState(test.total_time_seconds);
  const [showConfirm, setShowConfirm] = useState(false);
  const startTimeRef = useRef(Date.now());
  const handleSubmitRef = useRef<() => void>(() => {});
  const [timeExpired, setTimeExpired] = useState(false);
  const examInfo = getExamById(test.exam_id);
  const markingScheme = examInfo?.examPattern?.markingScheme;

  // Countdown timer and beforeunload protection
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      e.preventDefault();
      e.returnValue = "";
    };
    window.addEventListener("beforeunload", handleBeforeUnload);

    const interval = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(interval);
          setTimeExpired(true);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => {
      clearInterval(interval);
      window.removeEventListener("beforeunload", handleBeforeUnload);
    };
  }, []);

  const allQuestions = useMemo(() => test.sections.flatMap((s) => s.questions), [test.sections]);
  const currentSection = test.sections[activeSection];
  const sectionQuestions = currentSection?.questions || [];
  const currentQ = sectionQuestions[activeQuestion];

  const handleAnswer = (questionId: string, optionIndex: number) => {
    setAnswers((prev) => ({
      ...prev,
      [questionId]: prev[questionId] === optionIndex ? null : optionIndex,
    }));
  };

  const toggleFlag = (questionId: string) => {
    setFlagged((prev) => {
      const next = new Set(prev);
      if (next.has(questionId)) next.delete(questionId);
      else next.add(questionId);
      return next;
    });
  };

  const handleSubmit = useCallback(() => {
    const elapsedSeconds = Math.round((Date.now() - startTimeRef.current) / 1000);
    const { correct: correctMarks, wrong: wrongMarks } = parseMarkingScheme(markingScheme);
    let score = 0;
    let totalMarks = 0;

    allQuestions.forEach((q) => {
      totalMarks += correctMarks;
      const ans = answers[q.id];
      if (ans === q.answerIndex) score += correctMarks;
      else if (ans !== null && ans !== undefined) score += wrongMarks;
    });

    const finishedTest: MockTest = {
      ...test,
      answers,
      score,
      total_marks: totalMarks,
      time_taken_seconds: elapsedSeconds,
      status: "completed",
      completed_at: new Date().toISOString(),
    };

    setShowConfirm(false);
    onFinish(finishedTest);
  }, [answers, test, onFinish, allQuestions, markingScheme]);

  // Keep the ref up to date whenever handleSubmit recreates
  useEffect(() => {
    handleSubmitRef.current = handleSubmit;
  });

  // Trigger submit when timer expires (avoids side-effects inside setState)
  useEffect(() => {
    if (timeExpired) {
      handleSubmitRef.current();
    }
  }, [timeExpired]);

  const formatTime = (s: number) => {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const sec = s % 60;
    return h > 0
      ? `${h}:${m.toString().padStart(2, "0")}:${sec.toString().padStart(2, "0")}`
      : `${m}:${sec.toString().padStart(2, "0")}`;
  };

  const answeredCount = Object.values(answers).filter((v) => v !== null && v !== undefined).length;
  const isTimeLow = timeLeft < 300;

  return (
    <div className="min-h-screen flex flex-col bg-background">
      {/* Top bar */}
      <header className="glass border-b border-border px-4 py-3 flex items-center justify-between sticky top-0 z-30">
        <div className="flex items-center gap-3">
          <div className="font-bold font-heading">{test.exam_name}</div>
          <span className="text-xs text-muted-foreground">
            {answeredCount}/{allQuestions.length} answered
          </span>
        </div>
        <div
          className={cn(
            "flex items-center gap-2 px-3 py-1.5 rounded-full font-mono text-sm font-bold",
            isTimeLow ? "bg-destructive/15 text-destructive animate-pulse" : "bg-accent",
          )}
          style={isTimeLow ? undefined : { color: "var(--primary)" }}
        >
          <Timer className="h-4 w-4" />
          {formatTime(timeLeft)}
        </div>
        <Button variant="destructive" size="sm" onClick={() => setShowConfirm(true)}>
          <Flag className="h-3.5 w-3.5 mr-1" /> Submit
        </Button>
      </header>

      <div className="flex flex-1 overflow-hidden">
        {/* Question palette sidebar (desktop) */}
        <aside className="hidden lg:flex flex-col w-64 border-r border-border p-4 overflow-y-auto bg-sidebar">
          {test.sections.map((section, si) => (
            <div key={section.name} className="mb-4">
              <button
                onClick={() => {
                  setActiveSection(si);
                  setActiveQuestion(0);
                }}
                className={cn(
                  "text-xs font-semibold uppercase tracking-wider mb-2 w-full text-left px-1",
                  si === activeSection ? "text-primary" : "text-muted-foreground",
                )}
              >
                {section.name}
              </button>
              <div className="grid grid-cols-5 gap-1.5">
                {section.questions.map((q, qi) => {
                  const isActive = si === activeSection && qi === activeQuestion;
                  const isAnswered = answers[q.id] !== null && answers[q.id] !== undefined;
                  const isFlagged = flagged.has(q.id);
                  return (
                    <button
                      key={q.id}
                      onClick={() => {
                        setActiveSection(si);
                        setActiveQuestion(qi);
                      }}
                      className={cn(
                        "h-8 w-8 rounded-lg text-xs font-medium transition-all relative",
                        isActive
                          ? "bg-gradient-primary text-white shadow-glow-sm"
                          : isAnswered
                            ? "bg-success/15 text-success border border-success/30"
                            : "bg-muted/30 text-muted-foreground hover:bg-muted/50",
                      )}
                    >
                      {qi + 1}
                      {isFlagged && (
                        <div className="absolute -top-1 -right-1 w-2.5 h-2.5 rounded-full bg-warning" />
                      )}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}

          <div className="mt-auto pt-4 border-t border-border space-y-1.5 text-xs">
            <div className="flex items-center gap-2">
              <div className="h-3 w-3 rounded bg-success/15 border border-success/30" /> Answered
            </div>
            <div className="flex items-center gap-2">
              <div className="h-3 w-3 rounded bg-muted/30" /> Not answered
            </div>
            <div className="flex items-center gap-2">
              <div className="h-3 w-3 rounded bg-muted/30 relative">
                <div className="absolute -top-0.5 -right-0.5 w-1.5 h-1.5 rounded-full bg-warning" />
              </div>{" "}
              Flagged for review
            </div>
          </div>
        </aside>

        {/* Main question area */}
        <main className="flex-1 flex flex-col overflow-y-auto">
          {/* Section tabs (mobile + desktop) */}
          <div className="flex border-b border-border overflow-x-auto">
            {test.sections.map((section, si) => {
              const sectionAnswered = section.questions.filter(
                (q) => answers[q.id] !== null && answers[q.id] !== undefined,
              ).length;
              return (
                <button
                  key={section.name}
                  onClick={() => {
                    setActiveSection(si);
                    setActiveQuestion(0);
                  }}
                  className={cn(
                    "px-5 py-3 text-sm font-medium whitespace-nowrap border-b-2 transition-colors",
                    si === activeSection
                      ? "border-primary text-primary"
                      : "border-transparent text-muted-foreground hover:text-foreground",
                  )}
                >
                  {section.name}
                  <span className="ml-2 text-xs opacity-60">
                    {sectionAnswered}/{section.questions.length}
                  </span>
                </button>
              );
            })}
          </div>

          {/* Question content */}
          {currentQ && (
            <div className="flex-1 p-6 max-w-3xl mx-auto w-full">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-2">
                  <span
                    className="text-xs px-2.5 py-1 rounded-full font-medium"
                    style={{ background: "var(--accent)", color: "var(--primary)" }}
                  >
                    Q{activeQuestion + 1} of {sectionQuestions.length}
                  </span>
                  <span className="text-xs text-muted-foreground">{currentQ.topic}</span>
                </div>
                <button
                  onClick={() => toggleFlag(currentQ.id)}
                  className={cn(
                    "flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full transition-all",
                    flagged.has(currentQ.id)
                      ? "bg-warning/15 text-warning"
                      : "bg-muted/30 text-muted-foreground hover:bg-muted/50",
                  )}
                >
                  <Flag className="h-3 w-3" />
                  {flagged.has(currentQ.id) ? "Flagged" : "Flag"}
                </button>
              </div>

              <div className="text-lg font-medium leading-relaxed mb-6">{currentQ.question}</div>

              <div className="space-y-3">
                {currentQ.options.map((opt, oi) => {
                  const isSelected = answers[currentQ.id] === oi;
                  return (
                    <button
                      key={oi}
                      onClick={() => handleAnswer(currentQ.id, oi)}
                      className={cn(
                        "w-full text-left p-4 rounded-xl border transition-all duration-200 flex items-center gap-3",
                        isSelected
                          ? "border-[color:var(--feat-mock)] shadow-sm"
                          : "border-border hover:border-primary/20",
                      )}
                      style={
                        isSelected
                          ? { background: "var(--feat-mock-bg)" }
                          : { background: "var(--muted)" }
                      }
                    >
                      <div
                        className={cn(
                          "h-8 w-8 rounded-lg grid place-items-center text-sm font-bold shrink-0",
                          isSelected ? "bg-primary text-white" : "text-muted-foreground",
                        )}
                        style={isSelected ? undefined : { background: "var(--muted)" }}
                      >
                        {String.fromCharCode(65 + oi)}
                      </div>
                      <span className="text-sm">{opt}</span>
                    </button>
                  );
                })}
              </div>

              {/* Navigation */}
              <div className="flex items-center justify-between mt-8 pt-4 border-t border-border">
                <Button
                  variant="ghost"
                  disabled={activeQuestion === 0 && activeSection === 0}
                  onClick={() => {
                    if (activeQuestion > 0) {
                      setActiveQuestion(activeQuestion - 1);
                    } else if (activeSection > 0) {
                      setActiveSection(activeSection - 1);
                      setActiveQuestion(test.sections[activeSection - 1].questions.length - 1);
                    }
                  }}
                >
                  <ChevronLeft className="h-4 w-4 mr-1" /> Previous
                </Button>

                {/* Mobile question palette */}
                <div className="lg:hidden flex items-center gap-1 overflow-x-auto max-w-[150px]">
                  {sectionQuestions
                    .slice(
                      Math.max(0, activeQuestion - 2),
                      Math.min(sectionQuestions.length, activeQuestion + 3),
                    )
                    .map((q, i) => {
                      const realIdx = Math.max(0, activeQuestion - 2) + i;
                      const isAns = answers[q.id] !== null && answers[q.id] !== undefined;
                      return (
                        <button
                          key={q.id}
                          onClick={() => setActiveQuestion(realIdx)}
                          className={cn(
                            "h-7 w-7 rounded text-xs font-medium shrink-0",
                            realIdx === activeQuestion
                              ? "bg-gradient-primary text-white"
                              : isAns
                                ? "bg-success/15 text-success"
                                : "bg-muted/30 text-muted-foreground",
                          )}
                        >
                          {realIdx + 1}
                        </button>
                      );
                    })}
                </div>

                <Button
                  variant="ghost"
                  disabled={
                    activeSection === test.sections.length - 1 &&
                    activeQuestion === sectionQuestions.length - 1
                  }
                  onClick={() => {
                    if (activeQuestion < sectionQuestions.length - 1) {
                      setActiveQuestion(activeQuestion + 1);
                    } else if (activeSection < test.sections.length - 1) {
                      setActiveSection(activeSection + 1);
                      setActiveQuestion(0);
                    }
                  }}
                >
                  Next <ChevronRight className="h-4 w-4 ml-1" />
                </Button>
              </div>
            </div>
          )}
        </main>
      </div>

      {/* Submit confirmation modal */}
      {showConfirm && (
        <div
          className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4"
          onClick={() => setShowConfirm(false)}
        >
          <div
            className="card-light p-6 rounded-2xl max-w-sm w-full shadow-elegant"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="h-10 w-10 rounded-xl bg-warning/10 grid place-items-center">
                <AlertTriangle className="h-5 w-5 text-warning" />
              </div>
              <div>
                <div className="font-semibold">Submit test?</div>
                <div className="text-sm text-muted-foreground">This action cannot be undone.</div>
              </div>
            </div>
            <div
              className="text-sm space-y-1 mb-5 p-3 rounded-xl"
              style={{ background: "var(--muted)" }}
            >
              <div className="flex justify-between">
                <span className="text-muted-foreground">Answered</span>
                <span className="font-medium">
                  {answeredCount}/{allQuestions.length}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Unanswered</span>
                <span className="font-medium">{allQuestions.length - answeredCount}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Flagged</span>
                <span className="font-medium">{flagged.size}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Time left</span>
                <span className="font-medium">{formatTime(timeLeft)}</span>
              </div>
            </div>
            <div className="flex gap-3">
              <Button variant="ghost" className="flex-1" onClick={() => setShowConfirm(false)}>
                Continue
              </Button>
              <Button
                className="flex-1 bg-gradient-primary"
                onClick={() => {
                  setShowConfirm(false);
                  handleSubmit();
                }}
              >
                Submit
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* ──────────── RESULT SCREEN ──────────── */
function ResultScreen({ test, onBack }: { test: MockTest; onBack: () => void }) {
  const [reviewSection, setReviewSection] = useState(0);
  const [showReview, setShowReview] = useState(false);
  const pct = test.total_marks ? Math.round(((test.score ?? 0) / test.total_marks) * 100) : 0;
  // displayPct is clamped to [0, 100] for the visual ring — the actual score text is still accurate
  const displayPct = Math.max(0, Math.min(100, pct));
  const mins = test.time_taken_seconds ? Math.round(test.time_taken_seconds / 60) : 0;

  const allQuestions = test.sections.flatMap((s) => s.questions);
  const correct = allQuestions.filter((q) => test.answers[q.id] === q.answerIndex).length;
  const incorrect = allQuestions.filter(
    (q) =>
      test.answers[q.id] !== null &&
      test.answers[q.id] !== undefined &&
      test.answers[q.id] !== q.answerIndex,
  ).length;
  const unanswered = allQuestions.length - correct - incorrect;

  return (
    <div className="max-w-4xl mx-auto px-6 py-10 animate-fade-up">
      {/* Score hero */}
      <div className="card-light p-8 rounded-2xl text-center mb-6">
        <div
          className={cn(
            "inline-flex h-24 w-24 rounded-full items-center justify-center text-4xl font-bold font-heading mb-4",
            pct >= 70
              ? "bg-success/10 text-success"
              : pct >= 40
                ? "bg-warning/10 text-warning"
                : "bg-destructive/10 text-destructive",
          )}
        >
          {displayPct}%
        </div>
        <h1 className="text-2xl font-bold font-heading mb-1">
          {pct >= 70 ? "Excellent!" : pct >= 40 ? "Good effort!" : "Keep practicing!"}
        </h1>
        <p className="text-muted-foreground">
          You scored{" "}
          <strong className="text-foreground">
            {test.score}/{test.total_marks}
          </strong>{" "}
          marks in <strong className="text-foreground">{mins} minutes</strong>
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3 mb-6">
        <div className="card-light p-4 rounded-2xl text-center">
          <CheckCircle2 className="h-5 w-5 text-success mx-auto mb-1" />
          <div className="text-xl font-bold font-heading">{correct}</div>
          <div className="text-xs text-muted-foreground">Correct</div>
        </div>
        <div className="card-light p-4 rounded-2xl text-center">
          <XCircle className="h-5 w-5 text-destructive mx-auto mb-1" />
          <div className="text-xl font-bold font-heading">{incorrect}</div>
          <div className="text-xs text-muted-foreground">Incorrect</div>
        </div>
        <div className="card-light p-4 rounded-2xl text-center">
          <CircleDot className="h-5 w-5 text-muted-foreground mx-auto mb-1" />
          <div className="text-xl font-bold font-heading">{unanswered}</div>
          <div className="text-xs text-muted-foreground">Unanswered</div>
        </div>
      </div>

      {/* Section breakdown */}
      <div className="card-light p-5 rounded-2xl mb-6">
        <div className="flex items-center gap-2 mb-4">
          <BarChart3 className="h-4 w-4 text-primary" />
          <span className="font-semibold text-sm">Section Breakdown</span>
        </div>
        <div className="space-y-3">
          {test.sections.map((section) => {
            const sCorrect = section.questions.filter(
              (q) => test.answers[q.id] === q.answerIndex,
            ).length;
            const sPct = section.questions.length
              ? Math.round((sCorrect / section.questions.length) * 100)
              : 0;
            return (
              <div key={section.name}>
                <div className="flex items-center justify-between text-sm mb-1">
                  <span>{section.name}</span>
                  <span className="font-medium">
                    {sCorrect}/{section.questions.length} ({sPct}%)
                  </span>
                </div>
                <div
                  className="h-2 rounded-full overflow-hidden"
                  style={{ background: "var(--muted)" }}
                >
                  <div
                    className="progress-fill h-full rounded-full transition-all duration-700"
                    style={
                      {
                        "--pct": `${sPct}%`,
                        background: "var(--gradient-primary)",
                      } as React.CSSProperties
                    }
                  />
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Action buttons */}
      <div className="flex gap-3 mb-8">
        <Button variant="ghost" onClick={onBack} className="flex-1">
          <RotateCcw className="h-4 w-4 mr-2" /> New Test
        </Button>
        <Button className="flex-1 bg-gradient-primary" onClick={() => setShowReview(!showReview)}>
          <BookOpen className="h-4 w-4 mr-2" /> {showReview ? "Hide" : "Review"} Answers
        </Button>
      </div>

      {/* Answer review */}
      {showReview && (
        <div>
          <div className="flex border-b border-border mb-4 overflow-x-auto">
            {test.sections.map((section, si) => (
              <button
                key={section.name}
                onClick={() => setReviewSection(si)}
                className={cn(
                  "px-4 py-2.5 text-sm font-medium whitespace-nowrap border-b-2 transition-colors",
                  si === reviewSection
                    ? "border-primary text-primary"
                    : "border-transparent text-muted-foreground hover:text-foreground",
                )}
              >
                {section.name}
              </button>
            ))}
          </div>

          <div className="space-y-4">
            {test.sections[reviewSection]?.questions.map((q, qi) => {
              const userAnswer = test.answers[q.id];
              const isCorrect = userAnswer === q.answerIndex;
              const isUnanswered = userAnswer === null || userAnswer === undefined;
              return (
                <div key={q.id} className="card-light p-5 rounded-2xl">
                  <div className="flex items-center gap-2 mb-3">
                    <span
                      className={cn(
                        "h-6 w-6 rounded-full grid place-items-center text-xs",
                        isCorrect
                          ? "bg-success/10 text-success"
                          : isUnanswered
                            ? "bg-muted/30 text-muted-foreground"
                            : "bg-destructive/10 text-destructive",
                      )}
                    >
                      {isCorrect ? (
                        <CheckCircle2 className="h-3.5 w-3.5" />
                      ) : isUnanswered ? (
                        "−"
                      ) : (
                        <XCircle className="h-3.5 w-3.5" />
                      )}
                    </span>
                    <span className="text-sm font-medium">Q{qi + 1}</span>
                    <span className="text-xs text-muted-foreground">{q.topic}</span>
                  </div>

                  <div className="text-sm font-medium mb-3">{q.question}</div>

                  <div className="space-y-1.5 mb-3">
                    {q.options.map((opt, oi) => (
                      <div
                        key={oi}
                        className={cn(
                          "text-sm px-3 py-2 rounded-lg",
                          oi === q.answerIndex
                            ? "bg-success/10 text-success border border-success/20"
                            : oi === userAnswer && oi !== q.answerIndex
                              ? "bg-destructive/10 text-destructive border border-destructive/20"
                              : "text-muted-foreground",
                        )}
                      >
                        <span className="font-medium mr-2">{String.fromCharCode(65 + oi)}.</span>
                        {opt}
                      </div>
                    ))}
                  </div>

                  <div
                    className="text-xs text-muted-foreground p-3 rounded-lg"
                    style={{
                      background: "var(--accent)",
                      borderColor: "var(--primary)",
                      borderWidth: "1px",
                      borderStyle: "solid",
                      opacity: 0.7,
                    }}
                  >
                    <span className="text-xs font-semibold text-foreground uppercase tracking-wide block mb-1">
                      Explanation
                    </span>
                    <MarkdownContent content={q.explanation || ""} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
